version: 2

builds:
  - main: ./cmd/noisepan/
    binary: noisepan
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
      - -X github.com/ppiankov/noisepan/internal/cli.Version={{.Version}}
      - -X github.com/ppiankov/noisepan/internal/cli.Commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: ppiankov
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ppiankov/noisepan"
    description: "Extract signal from noisy information streams"
    license: MIT
    install: |
      bin.install "noisepan"
    test: |
      system "#{bin}/noisepan", "version"
